steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/mycdcigcp/my-docker-repo/my-image:latest",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/mycdcigcp/my-docker-repo/my-image",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "my-image",
        "--image",
        "asia-northeast1-docker.pkg.dev/mycdcigcp/my-docker-repo/my-image:latest",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--ingress",
        "all",
        "--region",
        "asia-northeast1",
        "--project",
        "mycdcigcp",
        "--quiet"
      ]

logsBucket: "gcs_bucket_name"
serviceAccount: "projects/mycdcigcp/serviceAccounts/ca-build-cicd@mycdcigcp.iam.gserviceaccount.com"
options:
  logging: GCS_ONLY
